import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";
import Helmet from "react-helmet";
import NewsletterModal from "~/components/features/modals/newsletter-modal";
import IntroSection from "~/components/partials/home/carosel";
import IntroBanners from "~/components/partials/home/intro-banners";
import DealSection from "~/components/partials/home/deal-section";
import InstagramSection from "~/components/partials/home/instagram-section";
import useCurrentUser from "~/lib/hook/useCurrentUser";

export default function Home() {
  const { currentUser, fetcherWithToken } = useCurrentUser();
  useEffect(() => {
    console.log(currentUser);
  }, [currentUser]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Helmet>
        <title>Riode React eCommerce Template - Home</title>
      </Helmet>
      <div className="page-content">
        <IntroSection />
        <IntroBanners />

        <DealSection />
        <InstagramSection />
      </div>
      <NewsletterModal />
    </div>
  );
}
