import Head from "next/head";
import Helmet from "react-helmet";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Helmet>
        <title>Riode React eCommerce Template - Home</title>
      </Helmet>
      <div className="page-content">1111111111111111</div>
    </div>
  );
}
